language: java
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "apache"

jobs:
    include:
        - name: "Java 8"
          jdk: openjdk8
           script: mvn clean install sonar:sonar -Dsonar.organization=apache -Dsonar.projectKey=apache_incubator-tamaya

        - name: "Java 9"
          jdk: openjdk9
          script: mvn clean install

        - name: "Java 10"
          jdk: openjdk10
          script: mvn clean install

        - name: "Java 11"
          jdk: openjdk11
          script: mvn clean install


