// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

= Apache Tamaya -- Extension: Events

toc::[]


[[Core]]
== Tamaya Events (Extension Module)
=== Overview

Tamaya Events is an extension module. Refer to the link:modules.html[extensions documentation] for further details
about modules.

Tamaya Events provides an abstraction for events like change events, when configuration has been changed.

=== Compatibility

The module is based on Java 7, so it can be used with Java 7 and beyond.

=== Installation

To benefit from configuration event support you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-events</artifactId>
  <version>{tamayaVersion}</version>
</dependency>
-----------------------------------------------

=== Core Architecture

The core of the module are the +ConfigEventListener+ interface and the +ConfigEvent+ class, which defines an abstraction
for event handling and observation:

[source,java]
.ConfigEvent
--------------------------------------------
public final interface ConfigEvent<T> {

    Class<T> getResourceType();
    T getResource();
    String getVersion();
    long getTimestamp();
}

// @FunctionalInterface
public interface ConfigEventListener {

    void onConfigEvent(ConfigEvent<?> event);

}
--------------------------------------------

This mechanism can now be used to propagate configuration changes to all interested stakeholders. Hereby the payload
can be basically arbitrary as long as it implements the +ConfigEvent+ interface. The next sections
give more details on the the provided event types and their usage.


=== Modelling Configuration Changes

This module provides a serializable and thread-safe abstraction modlling a configuration change. A change hereby may
be

* additional configuration entries
* removed configuration entries
* changes on entries


The most important event modelled is the +ConfigurationChange+ class, which implements the event sent for a changed
+Configuration+:

[source,java]
-------------------------------------------------------
public final class ConfigurationChange implements ConfigEvent<Configuration>, Serializable{

    public static ConfigurationChange emptyChangeSet(Configuration configuration);

    @Override
    public Configuration getResource();
    @Override
    public Class<Configuration> getResourceType();
    @Override
    public String getVersion();
    @Override
    public long getTimestamp();

    // Event specific methods

    public Collection<PropertyChangeEvent> getChanges();
    public int getRemovedSize();
    public int getAddedSize();
    public int getUpdatedSize();

    public boolean isKeyAffected(String key);
    public boolean isRemoved(String key);
    public boolean isAdded(String key);
    public boolean isUpdated(String key);
    public boolean containsKey(String key);
    public boolean isEmpty();
}

-------------------------------------------------------

New instances of this class hereby can be created using a fluent builder:

[source,java]
-------------------------------------------------------
Configuration config = ...;
ConfigurationChange change = ConfigurationChangeBuilder.of(config)
  .addChange("MyKey", "newValue")
  .removeKeys("myRemovedKey").build();
-------------------------------------------------------

Also it is possible to directly compare 2 instances of configurations to create +ConfigurationChange+ that
reflect the differences between the two configurations:

[source,java]
Comparing 2 configurations
-------------------------------------------------------
Configuration config = ...;
Configuration changedConfig = ...;
ConfigurationChange change = ConfigurationChangeBuilder.of(config)
  .addChanges(changedConfig).build();
-------------------------------------------------------

So a +ConfigurationChange+ allows you to evaluate the changes on a configuration. This allows you to listen to changes
and react in your client code as useful, once you encounter changes that are relevant to you, e.g. by reconfiguring
your component. For listening to configuration changes you must implement the
+ConfigEventListener+ functional interface:

[source,java]
.Implementing a ConfigChangeListener
-------------------------------------------------------
public final class MyConfigChangeListener implements ConfigChangeListener<ConfigurationChange>{

  private Configuration config = ConfigurationProvider.getConfiguration();

  public void onConfigEvent(ConfigEvent<?> event){
     if(event.getResourceTspe()==Configuration.class){
         if(event.getConfiguration()==config){
           // do something
         }
     }
  }

}
-------------------------------------------------------

You can *register* your implementation in 2 ways:

. Manually by calling +ConfigEventManager.addListener(new MyConfigChangeListener())+
. Automatically by registering your listener using the +ServiceLoader+ under
  +META-INF/services/org.apache.tamaya.events.ConfigEventListener+


=== Modelling PropertySource Changes

Beside that a whole configuration changes, also +PropertySource+ instances can change, e.g. by a configuration file
edited on the fly. This is similarly to a +ConfigurationChange+ reflected by the classes +PropertySourceChange,
PropertySourceChangeBuilder+.


=== The ConfigEventManager Singleton

Main entry point of the events module is the +ConfigEventManager+ singleton class, which provides static accessor
methods to the extension's functionality:

* Adding/removing of +ConfigChangeListener+ instances, either globally or per event type.
* Firing configuration events synchronously or asyncronously (mostly called by framework code).
* Configuring the monitor that periodically checks for changes on the global +Configuration+ provided
  by +ConfigurationProvider.getConfiguration()+.

[source,java]
-------------------------------------------------------
public final class ConfigEventManager {

    private ConfigEventManager() {}

    public static void addListener(ConfigEventListener l);
    public static <T extends ConfigEvent> void addListener(ConfigEventListener l, Class<T> eventType);
    public static void removeListener(ConfigEventListener l);
    public static <T extends ConfigEvent> void removeListener(ConfigEventListener l, Class<T> eventType);
    public static <T extends ConfigEvent>
        Collection<? extends ConfigEventListener> getListeners();
    public static <T extends ConfigEvent>
        Collection<? extends ConfigEventListener> getListeners(Class<T> type);

    public static <T> void fireEvent(ConfigEvent<?> event);
    public static <T> void fireEventAsynch(ConfigEvent<?> event);

    public static void enableChangeMonitoring(boolean enable);
    public static boolean isChangeMonitoring();
    public long getChangeMonitoringPeriod();
    public void setChangeMonitoringPeriod(long millis);

}
-------------------------------------------------------


==== Monitoring of configuration changes

The +ConfigEventManager+ also supports active monitoring of the current configuration to trigger corresponding change
events to listeners registered. This feature is deactivated by default, but can be enabled by calling
+ConfigEventManager.enableChangeMonitoring(true);+. This feature avoids regularly polling your local +Configuration+ for
any kind of changes. If a change has been encountered Tamaya identifies it and triggers corresponding
+ConfigurationChange+ events automatically.


=== Freezing Configurations and PropertySources

+Configuration+ instances as well as +PropertySources+ are explicitly not required to be serializable. To enable easy
serialization of these types a +Configuration+'s *current state can be frozen* (e.g. for later comparison with a newly
loaded version). Freezing hereby means

* all key/values are read-out by calling the +getProperties()+ method.
* a meta data entry is added of the form +_frozenAt=223273777652325677+, whichdefines the UTC timestamp in
  milliseconds when this instance was frozen.
* if not already defined an +_id+ property will be added to the +Configuration+ containing the
  identifier of the configuration.

In code freezing is a no-brainer:

[source,java]
.Freezing the current Configuration
--------------------------------------------------
Configuration config = ConfigurationProvider.getConfiguration();
Configuration frozenConfig = FrozenConfiguration.of(config);
--------------------------------------------------

... and similarly for a +PropertySource+:

[source,java]
.Freezing the current Configuration
--------------------------------------------------
PropertySource propertySource = ...;
PropertySource frozenSource = FrozenPropertySource.of(propertySource);
--------------------------------------------------



=== SPIs

This component also defines an additional SPI, which allows to adapt the implementation of the main +ConfigEventManager+
singleton. This enables, for example, using external eventing systems, such as CDI, instead of the default provided
simple SE based implementation. As normal, implementation must be registered using the current +ServiceContext+
active, by default using the Java +ServiceLoader+ mechanism.

[source,java]
.SPI: ConfigEventSpi
--------------------------------------------------
public interface ConfigEventManagerSpi {

        <T> void addListener(ConfigEventListener l);
        <T extends ConfigEvent> void addListener(ConfigEventListener l, Class<T> eventType);
        void removeListener(ConfigEventListener l);
        <T extends ConfigEvent> void removeListener(ConfigEventListener l, Class<T> eventType);
        Collection<? extends ConfigEventListener> getListeners();
        Collection<? extends ConfigEventListener> getListeners(Class<? extends ConfigEvent> eventType);

        void fireEvent(ConfigEvent<?> event);
        void fireEventAsynch(ConfigEvent<?> event);

        long getChangeMonitoringPeriod();
        void setChangeMonitoringPeriod(long millis);
        boolean isChangeMonitorActive();
        void enableChangeMonitor(boolean enable);
}
--------------------------------------------------


Summarizing with the events module you can easily observe configuration changes, record the
state of any configuration and compare configuration states to create and publish related
change events.


