// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

= Apache Tamaya -- Extension: Builder

toc::[]


[[BuilderCore]]
== Tamaya JSON (Extension Module)
=== Overview

The Tamaya json module provides support for reading configuration using the JSON format:


=== Compatibility

The module is based on Java 7, so it will not run on Java 7 and beyond.


=== Installation

To benefit from configuration builder support you only must add the corresponding dependency to your module:

[source, xml]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-json</artifactId>
  <version>{tamayaVersion}</version>
</dependency>
-----------------------------------------------


=== Reading configuration in JSON

For reading JSON based onfiguration most easily a +JSONFormat+ can be provided:

[source, java]
-----------------------------------------------
ConfigurationData dataRead = ConfigurationFormats.readConfig(
    getClassLoader().getResource("myFileConfig.json"), new JSONFormat()));
-----------------------------------------------

=== Examples

The JSON module adds instances of +ConfigurationFormat+ so JSON configuration can be read and mapped to the
according property maps. E.g. the following file is a simple and correct JSON configuration:

[source,listing]
----------------------------------------------------------------
{
  "a" : "A",
  "b" : "B",
  "c" : "C",
  "d" : {
      "o" : "O",
      "p" : "P"
    }
}
----------------------------------------------------------------


