// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

= Apache Tamaya -- Extension: Builder

include::temp-properties-files-for-site/attributes.adoc[]


[[BuilderCore]]
== Tamaya Builder (Extension Module)
=== Overview

The Tamaya builder module provides a generic (one time) builder for creating +Configuration+ instances,
e.g. as follows:

[source,java]
---------------------------------------------------------------
ConfigurationBuilder builder = new ConfigurationBuilder();
// do something
Configuration config = builder.build();
---------------------------------------------------------------

Basically the builder allows to create configuration instances completely independent of the current configuration
setup. This gives you full control on the +Configuration+ setup.

=== Compatibility

The module is based on Java 7, so it will run on Java 7 and does
not require Java 8. The +ConfigurationProvider+
as defined by the API, provides a builder instance for +ConfigurationContext+
in a similar way. A +Configuration+ can also be created by passing an instance of a +ConfigurationContext+:


=== Installation

To benefit from configuration builder support you only must add the corresponding
dependency to your module:

[source,xml,subs="verbatim,attributes"]
-----------------------------------------------
<dependency>
  <groupId>org.apache.tamaya.ext</groupId>
  <artifactId>tamaya-builder</artifactId>
  <version>{tamaya_version_development}</version>
</dependency>
-----------------------------------------------

=== Supported Functionality

The builder allows you to add +PropertySource+ instances:

[source,java]
----------------------------------------------------------------
ConfigurationBuilder builder = new ConfigurationBuilder();
builder.addPropertySources(sourceOne).addPropertySources(sourceTwo);
Configuration config = builder.build();
----------------------------------------------------------------

Similarly you can add filters:

[source,java]
----------------------------------------------------------------
builder.addPropertyFilters(new MyConfigFilter());
----------------------------------------------------------------

...or +PropertySourceProvider+ instances:

[source,java]
----------------------------------------------------------------
builder.addPropertySourceProvider(new MyPropertySourceProvider());
----------------------------------------------------------------

Also the builder module allows to include/exclude any filters and property source already known to the current
+ConfigurationContext+:

[source,java]
----------------------------------------------------------------
builder.disableProvidedPropertyConverters();
builder.enableProvidedPropertyConverters();

builder.disableProvidedPropertyFilters();
builder.enableProvidedPropertyFilters();

builder.disableProvidedPropertySources();
builder.enableProvidedPropertySources();
----------------------------------------------------------------
