= Apache Tamaya -- Extension: Formats

:name: Tamaya
:rootpackage: org.apache.tamaya.ext.formats
:title: Apache Tamaya Extension: Formats
:revnumber: 0.1.1
:revremark: Incubator
:revdate: March 2015
:longversion: {revnumber} ({revremark}) {revdate}
:authorinitials: ATR
:author: Anatole Tresch
:email: <anatole@apache.org>
:source-highlighter: coderay
:website: http://tamaya.incubator.apache.org/
:iconsdir: {imagesdir}/icons
:toc:
:toc-placement: manual
:icons:
:encoding: UTF-8
:numbered:
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
'''

<<<

toc::[]

<<<
:numbered!:
<<<
[[Core]]
== Tamaya Formats (Extension Module)
=== Overview

Tamaya Formats is an extension module. Refer to the link:modules.html[extensions documentation] for further details.

Tamaya Formats provides an abstraction for configuration formats provding the following benefits:

* Parsing of resources in can be implemented separately from interpreting the different aspects/parts parsed. As an
  example a file format can define different sections. Depending on the company specific semantics of the sections
  a different set of +PropertySource+ instances must be created.
* Similarly the configuration abstraction can also be used as an interface for integrating Tamaya with alternate
  frameworks that provide logic for reading configuration files, such as Apache commons.configuration.


=== The Idea

Formats should be reusable, meaning you should have to write a format parser only once and then be able to map the data read into whatever
data structure (in our cases: property sources).

==== ConfigurationData

Configuration formats can be very different. Some are simpley key/value pairs, whereas other also consist of multiple sections (e.g. ini-files) or
hierarchical data (e.g. yaml, xml). This is solved in Tamaya by mapping the configuration read into a normalized intermediary format called
+ConfigurationData+:

[source,java]
.ConfigurationData
-------------------------------------------------------
public final class ConfigurationData {

    public ConfigurationFormat getFormat();
    public String getResource();

    public boolean hasSections();
    public Set<String> getSectionNames();
    public Map<String,String> getSection(String name);
    public Map<String,Map<String,String>> getSections();

    public boolean hasDefaultProperties();
    public Map<String,String> getDefaultProperties();

    public Map<String,String> getProperties();
    public boolean hasCombinedProperties();

    public boolean isEmpty();
}
-------------------------------------------------------

In detail the data read from a file is organized into _sections_ as follows:

* with +getResource()+ and +getFormat()+ the underlying resource and the format that read this data can be accessed.
* a section contains a set of properties.
* it could be mapped to one single section, or to multiple sections. The method +getSectionNames()+ returns a set of all
  section names.
* it can have a _default_ properties, which basically contain data that may be not part of any section.
* With +getSection(String name)+ a section can be accessed by name.

Now for the conversion of +ConfigurationData+ into a +PropertySource+ different default approaches are used:

. The +ConfigurationFormat+ that read the data can provide the (combined) properties accessible from
  +getProperties()+ explcitly, which can be used to initialize a single +PropertySource+ containing the data read.
. If the format did not set the final properties, but only a default section is present this default section
  can be directly returned as combined properties.
. In all other cases a properties can be uniqiely mapped into one single properties Map, by prefixing all keys of each
  section present with the (unique) section name and a '.' separator.

Nevertheless, depending on the context, where a configuration source was read (classloader, time, source etc.) the
resulting +PropertySource+ can have different semnatics, especially for the +PropertySources+ ordinal. Also section
names may be mapped into different ordinals instead of using them as key prefixes (e.g. imagine configuration formats
with a 'default', 'main', and 'overrides' sections). For such more complex or custom cases no useful default mapping
can be defined. In such cases this functionality must be implemented in a _mapData_ method, which converts
the normalized +ConfigData+ read to the appropriate collection of +PropertySource+ instances:


==== ConfigurationFormat

A ConfigurationFormat is basically an abstraction that reads a configuration resource (modelled by an InputStream) and
creates a corresponding +ConfigurationData+ instance.

[source,java]
-------------------------------------------------------
public interface ConfigurationFormat {

    public String getName();
    boolean accepts(URL url);
    ConfigurationData readConfiguration(String resource, InputStream inputStream);
}
-------------------------------------------------------

Normally you need to map the resulting +ConfigurationData+ to one or multiple +PropertySources+. In case, where the
properties provided match exactly the extected properties a +FlattenedDefaultPropertySource+ is provided out-of-the-box.
If the exact mapping must be overridden, you can simply override the property source's initialize method to adapt the
mapping:

[source,java]
-------------------------------------------------------
ConfigurationData data = ...;
FlattenedDefaultPropertySource ps = new FlattenedDefaultPropertySource(data){
  protected Map<String, String> populateData(ConfigurationData data) {
    ...
  }
};
-------------------------------------------------------

