// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

<<<
[[UseCases]]
== Use Cases

This section describes some, but not all, of the use cases that should be covered by Tamaya.


[[UCSimpleAccess]]
=== Simple Property Access (UC 1)

Users just want to create a configuration (or configuration template) ad hoc, from given configuration files. The
files could be locally in the file system, on the classpath or remotely accessible by some URLs.

Tamaya should provide a simple Java API for accessing key/value based configuration. Hereby users want to access
properties as

* Strings
* Primitive types
* Wrapper types
* All other types


[[UCConfigInjection]]
=== Automatic Configuration (Configuration Injection, UC2)

Tamaya must provide a feature for automatic configuration, where properties of a class or methods can be annotated.

* Hereby the lifecycle of the instances configured should not be managed by Tamaya. Also users want to define default
values to be used in case no configured value is present.
* Users want to have callbacks so they can listen on configuration changes.
* Users want to evaluate multiple keys, e.g. current keys, and as a backup, deprecated keys
from former application releases.
* Users want to use dynamic placeholders in their value expressions.
* Users want to have full control about value evaluation and type conversion, if necessary.

To illustrate these points above imagine the following POJO:

[source, java]
.Configured POJO Example
----------------------------------------------------
public class MyPojo {
  @ConfigProperty("myCurrency")
  @DefaultValue("CHF")                       // use as default
  @WithLoadingPolicy(LoadingPolicy.INITIAL)  // load the value only once (no reinjection)
  private String currency;

  @ConfigProperty("myCurrencyRate")
  private Long currencyRate;

  @ConfigProperty                            // evaluates to key=<fieldName>="fullRate"
  @ConfigProperty("fallback.property")
  @WithConfig("default")
  @WithConfig("moduleConfig");
  private BigDecimal fullRate;

  // Configuration method
  void setStartup(@ConfigProperty boolean startup, @ConfigProperty("componentName") @WithConfig("module1") @DefaultValue("N/A") String compName){
     ...
  }

  // Configuration method
  @ConfigProperty("componentName")
  @WithConfig("module1")
  @DefaultValue("N/A")
  private void setComponentName(String compName){
     ...
  }

  // Configuration listener method, defining which properties to listen for
  @ConfigChanges
  @ConfigProperty("componentName")
  private void setComponentName(ConfigChange change){
     ...
  }

}
----------------------------------------------------

The instance then can be passed for being configured:

[source, java]
.Configuring a POJO
----------------------------------------------------
MyPojo instance = new MyPojo();
Configuration.configure(instance);
----------------------------------------------------

This will configure all values according to the load policies (by default +LoadPolicy.INITIAL+). Depending on the
listeners present and the properties injected Tamaya will keep weak references to the bean and the current environment,
so it can be determined, when configuration changes must be published into the bean.

[[UCTemplates]]
=== Configuration Templates (UC3)

For type safe configuration clients should be able to define an interface and let it implement by the
configuration system based on configuration available. Following an example template is shown, which illustrates
annotating an interface with the same annotations as for configured classes:

[source, java]
.Type Safe Configuration Template Example
----------------------------------------------------
public interface MyConfig {

  @ConfiguredProperty("myCurrency")
  @DefaultValue("CHF")
  String getCurrency();

  @ConfiguredProperty("myCurrencyRate")
  Long getCurrencyRate();

  @ConfigChange
  default configChanged(ConfigChange event){
     ...
  }

}
----------------------------------------------------

The configuration system will then provide the interface as follows:

[source, java]
.Accessing a type safe Configuration Template
----------------------------------------------------
MyConfig config = Configuration.current(MyConfig.class);
----------------------------------------------------

Finally a +Configuration+ itself can be accessed as template as well, which
provides full access to all features:

[source, java]
.Accessing a Configuration
----------------------------------------------------
Configuration config = Configuration.current(Configuration.class);
----------------------------------------------------


[[UCSimpleConfiguration]]
=== Simple Property Based Configuration (UC4)

In this most simple usage scenario an application is configured by some property files contained in the
Java archive. Tamaya should provide a reasonable default meta-model, if no meta-model is currently loaded.

Additionally users want (optionally) to override settings by applying system properties or other command line
arguments.


[[UCAdvancedPropertyBasedConfiguration]]
=== Advanced Property Based Configuration (UC5)

Enhancing the previous scenario, we might as well consider the current environment. Saying that our overriding mechanisms
must be improved, since people do not want all properties to be mutable.
Dynamic placeholders should be supported for values.
It is also possible to add environment values to a configuration.

[[UCModularizedConfiguration]]
=== Modularized Configuration (UC6)

When systems grow they must be modularized to keep control. Whereas that sounds not really fancy, it leads to additional
aspects to be considered by a configuration system.

* Different code modules want to have their "own" configuration.
* Some modules require a certain subset of keys to be read at once into a Map.
* Products contain multiple modules, which per product are configured separately.


[[UCTypeSupport]]
=== Extended Type Support (UC7)

Application configuration must also support non String types such as primitives, wrapper types, math types
and date/time values. Basically each type that can be created from a String in more standardized way should
supported. This should be even possible for types not known at build time of possible. Type conversion hereby
should be flexible and extensible.

[[UCDynamicProvisioning]]
=== Dynamic Provisioning (UC8)

In Cloud Computing, especially the PaaS and SaaS areas a typical use case would be that an application (or server)
is deployed, configured and started dynamically. Typically things are controlled by some "active controller components",
which are capable of
* creating new nodes (using IaaS services)
* deploying and starting the required runtime platform , e.g. as part of a PaaS solution.
* deploying and starting the application modules.

All these steps require some kind of configuration. As of today required files are often created on the target node
before the systems are started, using proprietary formats and mechanism. Similarly accessing the configuration in place
may require examining the file system or using again proprietary management functions. Of course, a configuration
solution should not try to solve that, but it can provide a significant bunch of functionality useful in such scenarios:

* provide remote capabilities for configuration
* allow configuration to be updated remotely.
* allow client code to listen for configuration changes and react as needed.


[[UCJavaEE]]
=== Java EE (UC9)

Considering Java EE different aspects should be considered:

* Java EE is a complex multi-layered architecture with different levels of runtime contexts:
** application server boot level (system classloader),
** (optional) deployment/undeployment of ears (ear classloader),
** (optional) deployment/undeployment of web applications (war classloader),
** different runtime setups, e.g. EJB calls, MDB execution, Servlet Requests, scheduled and timed executions.
* Configuring administrative resources (e.g. datasources, users, security etc) is typically vendor specific.
* The environment is inherently multi-threaded.

[[UCMultiTenancy]] (UC10)
=== Scenario MultiTenancy
In multi tenancy setups a hierarchical/graph model of contexts for configurations is required. For example there might
be some kind of layering as follows:

* Layer 0: Low level system configuration
* Layer 1: Domain configuration
* Layer 2: Default App configuration
* Layer 3: Tenant specific configuration
* Layer 4: User specific configuration


[[UCJavaAPI]] (UC11)
=== Accessing Configuration

So far we described much how configuration must be organized and managed, but we got not concrete, how it is accessed.
Basically there are two basic scenarios to be distinguished, which mainly depend on the way how the lifecycle of a component
to be configured is managed:

* If the lifecycle is managed manually by the developer, the configuration system
** can inject configuration values, when explicitly called to to so
** can provide an accessor for configuration.
* If the lifecycle is managed by some container such as a DI container, the configuration
  system should leverage the functionality of the container, where possible.


[[UCTesting]]
=== Testing (UC12)
When testing a Java solution, it must be possible to easily control the configuration provided, so isolated
component tests can be written effectively. Also it should be possible to control/isolate the configuration level for
each test case.

-> isolation of configuration services is required

-> API for controlling the configuration provided, required for according implementations in the testing frameworks.

[[UCStaging]]
=== Staging (UC13)
Different companies go through different staging levels during the development of software components. Currently only
rarely the EE frameworks support staging aspects, nevertheless no broader, well modelled staging concept is defined.
Different companies also have different staging or sub-staging levels in place, which also must be reflected.
Especially with sub-stages inheritance of stage related configuration is common sense and should be supported.

-> Main stages available and to be supported must be defined.

-> Enable additional stages to be added, so also custom stages can be supported.


[[UCCotsIntegration]]
=== Custom of the Shelf (COTS) Integration (UC14)
When buying software from an external software company it is often very cumbersome to integrate, adapt and customize
third party software to the internal operational requirements. Especially, when software is delivered as ear modules
portability is often very difficult and time consuming. Configuration should enable COTS providers to define a
customization contract, which also can be part of the COTS software interface and integration specifications. This
would allow operations to better control and configure third party solutions as possible, whereas in the evaluation
phase the integration and configuration options can explicitly be defined.

-> It must be possible to document configuration aspects supported.

-> Configuration must be adaptable from external sources (the operations which must operate the COTS solution).

