// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
<<<
[[CoreConcepts]]
== {name} Core Implementation Concepts
Tamaya comes with an implementation module that implements the Tamaya API. The API itself does only provide the API for configuration usage.
Especially it does not define how the current runtime +Environment+ is mapped to a +Configuration+. This the gaop that should be solved
by the core library.

The high level packages give you a good overview of the functionality provided:

* +org.apache.tamaya.core+ is the root package of the Tamaya core implementation.
* +org.apache.tamaya.core.config+ provides



The SPI contains the following core concepts/artifacts:

* _Bootstrap_ is the delegate singleton that is used by the framework to resolve components. The effective component
  loading can be accessed by implementing and registering an instance of +ServiceProvider+ using +java.util.ServiceLoader+.
* All the singleton used explicitly (+PropertyAdapters,PropertyProviders+ are backed up corresponding API interfaces.
  To override a singleton's behaviour the corresponding SPI has to be implemented and registered, so it can be loaded
  by the current +Bootstrap+ setup (by default ServiceLoader based).
* Also the singleton used implicitly by +Configuration, Environment, Stage+ are backed up corresponding SPI interfaces.
  To override a singleton's behaviour the corresponding SPI has to be implemented and registered, so it can be loaded
  by the current +Bootstrap+ setup (by default ServiceLoader based).

This is also reflected in the main parts of the API, which is quite small:

* +org.apache.tamaya+ contains the main abstractions +Configuration, ConfigOperator, ConfigQuery, PropertyAdapter, Stage,
  Environment, PropertyProvider, MetaInfo+
* +org.apache.tamaya.spi+ contains the SPI interfaces to be implemented by implementations and the +Bootstrap+ mechanism.
+ +org.apache.tamaya.annot+ contains the annotations defined.
